typography_spectrum: 0.1625951
color:
  saturation: 0.8119908
  lightness: 0.6175696
  brandStrength: 0.1315179
  rhythmicContrast: 0.7007948
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.5161979
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3a3a5ff5-bcb6-40df-a22d-72504d329588.png
name: Property Manager
navigation:
  - name: Property Manager
    url: 'https://propertymanager.strawberry-estate.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bde2aa94-7bb1-432e-a0a1-9e7053aeb5e4.ico
title: Property Manager
description: Cloud Based Management
